#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.


sudo apt update
sudo apt install haproxy -y
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver server1 52.86.245.35:80 check\n\tserver server2 18.234.129.196:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
