#!/usr/bin/env bash
# Bash (init) script 101-manage_my_process that manages manage_my_process
# When passing the argument start:
# Starts manage_my_process
# Creates a file containing its PID in /var/run/my_process.pid
# Displays manage_my_process started
# When passing the argument stop:
# Stops manage_my_process
# Deletes the file /var/run/my_process.pid
# Displays manage_my_process stopped
# When passing the argument restart
# Stops manage_my_process
# Deletes the file /var/run/my_process.pid
# Starts manage_my_process
# Creates a file containing its PID in /var/run/my_process.pid
# Displays manage_my_process restarted
# Displays Usage: manage_my_process


display_usage() {
  echo "Usage: $0 {start|stop|restart}"
}

# Check the arguments
case "$1" in
  start)
    # Start manage_my_process
    ./manage_my_process start
    ;;
  stop)
    # Stop manage_my_process
    ./manage_my_process stop
    ;;
  restart)
    # Restart manage_my_process
    ./manage_my_process restart
    ;;
  *)
    # Display usage if no or invalid argument is passed
    display_usage
    ;;
esac
